apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: ca
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-local
        namespace: flux-local
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server   
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: minikube
        cloudNativeServices: false
        kubernetesUrl: https://20.255.250.219:18443
      vault:
        type: hashicorp
        network: fabric
        address: http://10.0.0.4:8200
        authPath: localmanufacturer
        secretEngine: secretsv2
        secretPrefix: "data/localmanufacturer"
        role: vault-role
        tls: false
      proxy:
        provider: none
        externalUrlSuffix: develop.local.com

    storage:
      size: 512Mi
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      allowedTopologies:
        enabled: false

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:1.4.8
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: manufacturer-admin
      adminPassword: manufacturer-adminpw
      subject: "/C=CH/ST=Zurich/L=Zurich/O=Manufacturer/CN=ca.manufacturer-net"
      clusterIpPort: 7054

